version: '3.9'
services:
  #MongoDB services
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #API service
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}